openapi: 3.0.3
info:
  version: 0.0.1
  title: SuitApp API
  license:
    name: MIT
servers:
  - url: http://localhost
tags:
  - name: product
    description: CRUDS for a product
paths:
  /suit/api/v1/product/create:
    $ref: './spec-suit-api-product.yaml#/paths/~1create'

components:
  schemas:

    BaseMessage:
      type: object
      description: Base class to all requests
      properties:
        messageType:
          description: A discriminator containing the message class type and used to deserialization
          type: string
          title: Discriminator
          example:
            CreateProductRequest
      discriminator:
        propertyName: messageType

    BaseRequest:
      type: object
      description: Base class to all requests
      properties:
        requestId:
          type: string
          description: The id of request entity
          example: reqID:0001

    BaseResponse:
      type: object
      description: Base class to all responses
      properties:
        requestId:
          type: string
          example: reqID:0001
        result:
          type: string
          enum:
            - success
            - error
        errors:
          type: array
          items:
            $ref: '#/components/schemas/RequestError'

    RequestError:
      type: object
      description: Description of request processing error
      properties:
        message:
          type: string
        field:
          type: string
